import { generateSessionDebrief } from '../lib/interview/analytics';
import { AnswerState } from '../lib/interview/storage';

function assert(condition: boolean, msg: string) {
  if (!condition) throw new Error(msg);
  console.log('✅ ' + msg);
}

try {
  console.log('--- Testing Interview Debrief Insights ---');

  // 1. Insufficient Data (No Answers)
  const emptyAnswers: Record<string, AnswerState> = {};
  const emptyDebrief = generateSessionDebrief(emptyAnswers, 300);
  assert(emptyDebrief.hasGenuineEvals === false, 'Insufficient data sets hasGenuineEvals to false');
  assert(emptyDebrief.pacingInsight === '', 'Insufficient data sets no pacing insight');

  // 2. Insufficient Data (Only Fallbacks)
  const fallbackAnswers: Record<string, AnswerState> = {
    'q1': {
      questionId: 'q1',
      text: 'My answer',
      evaluationStatus: 'fallback',
      aiError: 'Failed',
      // Note: A true fallback generated by the current system evaluates status as 'fallback' and has no evaluation object
    },
    'q2': {
      questionId: 'q2',
      text: 'My second answer',
      evaluationStatus: 'evaluated',
      evaluation: {
        score: 65,
        technicalAccuracy: 65,
        relevance: 65,
        completeness: 65,
        communication: 65,
        strengths: ["Provided an answer"],
        improvements: ["Could provide more detail"],
        idealAnswer: "A more detailed response."
      }
    }
  };
  const fallbackDebrief = generateSessionDebrief(fallbackAnswers, 150);
  assert(fallbackDebrief.hasGenuineEvals === false, 'Fallback evaluation is excluded correctly');

  // 3. Normal Completed Interview (With Pacing & Genuine Evals)
  const normalAnswers: Record<string, AnswerState> = {
    'q1': {
      questionId: 'q1',
      text: 'Genuine text',
      evaluationStatus: 'evaluated',
      evaluation: {
        score: 85,
        technicalAccuracy: 90,
        relevance: 80,
        completeness: 70, // Weakest
        communication: 100,
        strengths: ['Great!'],
        improvements: ['More complete?'],
        idealAnswer: 'Ideal text'
      }
    },
    'q2': {
      questionId: 'q2',
      text: 'Genuine text 2',
      evaluationStatus: 'evaluated',
      evaluation: {
        score: 85,
        technicalAccuracy: 90,
        relevance: 80,
        completeness: 80,
        communication: 90,
        strengths: ['Great!'],
        improvements: ['More complete?'],
        idealAnswer: 'Ideal text'
      }
    }
  };
  
  // Elapsed time: 40 seconds / 2 questions = 20 sec per answer (Too fast)
  const fastDebrief = generateSessionDebrief(normalAnswers, 40);
  assert(fastDebrief.hasGenuineEvals === true, 'Normal answers produce genuine evals');
  assert(fastDebrief.avgComp === 75, 'Averages are computed correctly (70+80)/2 = 75');
  assert(fastDebrief.priorityDimension === 'Completeness', 'Lowest score (<80) is flagged as priority improvement');
  assert(fastDebrief.pacingInsight.includes('very quickly'), 'Fast pacing correctly identified');

  // Elapsed time: 400 seconds / 2 questions = 200 sec per answer (Too slow)
  const slowDebrief = generateSessionDebrief(normalAnswers, 400);
  assert(slowDebrief.pacingInsight.includes('quite long'), 'Slow pacing correctly identified');

  // Elapsed time: 150 seconds / 2 questions = 75 sec per answer (Sweet spot)
  const sweetSpotDebrief = generateSessionDebrief(normalAnswers, 150);
  assert(sweetSpotDebrief.pacingInsight.includes('sweet spot'), 'Sweet spot pacing correctly identified');

  console.log('\nAll tests passed successfully!');
} catch (e) {
  console.error('❌ Test failed:', e);
  process.exit(1);
}
